version: "3"

networks:
    laravel:

services:
    nginx:
        container_name: nginx
        build:
            context: .docker
            dockerfile: nginx.dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
    php:
        build:
            context: .docker
            dockerfile: php.dockerfile
        container_name: php
        image: php:8.2-fpm-alpine
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
    mysql:
        container_name: mysql
        image: mysql:5.7.32
        environment:
            MYSQL_DATABASE: onlineshop
            MYSQL_USER: shop
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel
