version: "3"

networks:
    laravel:

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel
    php:
        container_name: php
        image: php:8.2-fpm-alpine
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel
    mysql:
        container_name: mysql
        image: mysql:5.7.32
        environment:
            MYSQL_DATABASE: onlineshop
            MYSQL_USER: shop
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel
