version: "3"

networks:
    laravel:

services:
    #    nginx:
    #        container_name: nginx
    #        build:
    #            context: .docker
    #            dockerfile: nginx.dockerfile
    #        ports:
    #            - "80:80"
    #            - "443:443"
    #        volumes:
    #            - ./:/var/www/html
    #        networks:
    #            - laravel
    php:
        build:
            context: .docker
            dockerfile: php.dockerfile
        container_name: onlineshop
        image: php:8.3-fpm
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
    postgres:
        container_name: postgres
        image: 'postgres:15.2'
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: onlineshop
        volumes:
            - ./db/postgres/:/var/lib/postgresql/data/
        networks:
            - laravel
